// 分野IDと表示ラベルのマッピング（fields テーブルのマスターデータと一致させる）
export const FIELD_ID_LABELS: Record<string, string> = {
  public_infrastructure: "公的機関・社会インフラ",
  business: "企業・ブランド・サービス",
  tech: "IT・テック・Web",
  visual_arts: "漫画・イラスト・アート",
  video: "映像作品（実写・アニメ）",
  games: "ゲーム・玩具・キャラクター",
  music: "音楽・声優・サウンド",
  entertainment: "芸能・タレント・配信",
  publishing: "出版・文芸",
  sports: "スポーツ・公営競技",
  local: "飲食・観光・地域文化",
  fashion: "美容・ファッション・装い",
  lifestyle: "探究・趣味・暮らし",
  bot: "bot・定期配信",
};

export const OLD_CATEGORIES = [
  "政府・省庁・国会議員",
  "地方自治体・地方議員",
  "権利・社会",
  "福祉・ボランティア",
  "教育機関",
  "学者・研究者・科学者",
  "学生活動",
  "気象・災害",
  "報道（マスメディア）",
  "報道（個人・その他団体）",
  "ネットメディア",
  "水族館・動植物園",
  "博物館・美術館・展覧会",
  "美術家・芸術家",
  "写真・カメラ（個人・団体）",
  "映像制作（個人・団体）",
  "アニメ（作品）",
  "アニメ（個人・団体）",
  "漫画家・イラストレーター",
  "漫画作品",
  "小説家・作家",
  "出版・書店",
  "文房具・事務用品",
  "同人活動（個人・団体）",
  "ゲーム（個人・団体）",
  "おもちゃ",
  "音楽（個人・団体）",
  "声優",
  "テレビ番組・実写映画",
  "ラジオ番組・その他放送",
  "タレント・モデル",
  "テクノロジー（個人・団体・技術領域）",
  "ネットサービス",
  "配信系",
  "飲食",
  "動物カフェ・いきものアカウント",
  "キャラクター・マスコット",
  "観光",
  "交通・乗り物",
  "神社仏閣・宗教",
  "医療・ヘルスケア（個人・団体）",
  "美容・ファッション",
  "雑貨・インテリア",
  "スポーツ",
  "その他著名人",
  "その他企業・団体",
  "その他サービス・作品",
] as const;

// transition_status の選択肢。value は DB に保存される英語値
export const STATUS_OPTIONS = [
  { value: "", label: "（選択してください）" },
  { value: "not_migrated", label: "未移行（未確認）" },
  { value: "account_created", label: "アカウント作成済" },
  { value: "dual_active", label: "両方運用中" },
  { value: "migrated", label: "Bluesky 完全移行" },
  { value: "unverifiable", label: "確認不能" },
] as const;

export const EVIDENCE_SHORTCUTS: { label: string; template: string | null }[] = [
  { label: "（選択してください）", template: null },
  { label: "カスタムドメインのため", template: "カスタムドメインのため" },
  { label: "X/Twitter プロフィールに記載あり", template: "X/Twitter プロフィールに記載あり" },
  { label: "X/Twitter での言及", template: "X/Twitter での言及あり\nURLは\n\nです。" },
  { label: "公式サイトにリンクあり", template: "公式サイトにリンクあり\nURLは\n\nです。" },
  { label: "その他", template: "同一だとわかる客観的根拠として\n\nがあります。" },
];
