name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *" # 06:00 in JST
    - cron: "0 9 * * *" # 18:00 in JST

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear Cache
        run: |
          rm -rf ~/.npm
          rm -rf node_modules

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN --yes
