name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *" # 06:00 in JST
    - cron: "0 9 * * *" # 18:00 in JST

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - uses: amondnet/vercel-action@v25
        with:
          vercel-version: latest
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./
